export const ACTION_TYPES = {
  LINE_ADDED: "LINEA_AÑADIDA",
  LINE_SUPERSEDED: "LINEA_REEMPLAZADA",
  LINE_DECREMENTED: "LINEA_SUSTRAIDA",
  LINE_VOIDED: "LINEA_ANULADA",
  LINE_CANCELLED: "LINEA_CANCELADA",
  //COCINA
  LINE_READY: "LINEA_LISTA",
  LINE_SERVED: "LINEA_SERVIDA",
  LINE_PREPARATION_STARTED: "LINEA_PREPARACION_COMENZADA",
  //RESTO
  PAYMENT_ADDED: "PAGO_AÑADIDO",
  ACTION_REVERTED: "ACCION_REVERTIDA",
  SENT_TO_KITCHEN: "ENVIADO_A_COCINA",
  TICKET_CREATED: "TICKET_CREADO",
  TICKET_CLOSED: "TICKET_CERRADO",
};
